#!/bin/sh
### BEGIN INIT INFO
# Provides:          aesdsocket
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     S
# Default-Stop:      0 1 6
# Short-Description: Start/stop aesdsocket daemon
### END INIT INFO

DAEMON=/usr/bin/aesdsocket
DAEMON_OPTS="-d"
NAME=aesdsocket
DESC="AESD socket daemon"
PIDFILE=/var/run/${NAME}.pid

. /lib/lsb/init-functions

start() {
    log_daemon_msg "Starting $DESC" "$NAME"
    rm -f /var/tmp/aesdsocketdata.txt  # Xoá file cũ trước
       echo "Đã xoá /var/tmp/aesdsocketdata.txt"
    start-stop-daemon --start --quiet --background \
        --make-pidfile --pidfile "$PIDFILE" \
        --exec "$DAEMON" -- $DAEMON_OPTS
    log_end_msg $?
}

stop() {
    log_daemon_msg "Stopping $DESC" "$NAME"
    start-stop-daemon --stop --quiet --pidfile "$PIDFILE" --retry TERM/30/KILL/5
    RET=$?
    [ -f "$PIDFILE" ] && rm -f "$PIDFILE"
    log_end_msg $RET
}

case "$1" in
    start)  start ;;
    stop)   stop ;;
    restart|reload)
        stop
        start
        ;;
    status)
        status_of_proc -p "$PIDFILE" "$DAEMON" "$NAME" && exit 0 || exit $?
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
